export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  DIFFERENT_SIGN_IN_METHOD: "DIFFERENT_SIGN_IN_METHOD",
  PASSWORD_NOT_FOUND: "PASSWORD_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
} as const;
