import type { Column } from "@/shared/ui/Table/Table";

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  createdon: string;
  status: string;
  lastlogin: string;
}

export const columns: Column<User>[] = [
  { key: "id", header: "ID", width: "w-35" },
  { key: "name", header: "NAME", width: "w-40" },
  { key: "email", header: "EMAIL", width: "w-40" },
  { key: "role", header: "ROLE", width: "w-35", badge: true, align: "center" },
  { key: "createdon", header: "CREATED ON", width: "w-40" },
  {
    key: "status",
    header: "STATUS",
    width: "w-30",
    badge: true,
  },
  { key: "lastlogin", header: "LAST LOGIN", width: "w-40" },
];

export const data: User[] = [
  {
    id: "SETN-USR-01",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-02",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-03",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-04",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-05",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-03",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-06",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-07",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-08",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-04",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-09",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-10",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-11",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-12",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-13",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-14",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-15",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-16",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-17",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-18",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-19",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-20",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-21",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-22",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-23",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-24",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-25",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-26",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-27",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-28",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-29",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-30",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-31",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-32",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-33",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-34",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-35",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-01",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-02",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-03",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-04",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-05",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-03",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-06",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-07",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-08",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-ADN-04",
    name: "RDJ",
    email: "example@gmail.com",
    role: "Admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Active",
    lastlogin: "Sep 15, 2025 - 11:00 AM",
  },
  {
    id: "SETN-USR-09",
    name: "Test Account",
    email: "test@gmail.com",
    role: "volunteer",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-10",
    name: "Test Account",
    email: "test@gmail.com",
    role: "admin",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-11",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-12",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-13",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-14",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-15",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-16",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-17",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-18",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-19",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-20",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-21",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-22",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-23",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-24",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-25",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-26",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-27",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-28",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-29",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-30",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-31",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-32",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-33",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-34",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
  {
    id: "SETN-USR-35",
    name: "Test Account",
    email: "test@gmail.com",
    role: "Student",
    createdon: "Sep 15, 2025 - 11:00 AM",
    status: "Pending",
    lastlogin: "-",
  },
];
