// export type errorCodes =
//   | "INVALID_CREDENTIALS"
//   | "USER_NOT_FOUND"
//   | "EMAIL_NOT_VERIFIED"
//   | "DIFFERENT_SIGN_IN_METHOD";

export const errorCodeEnum = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  DIFFERENT_SIGN_IN_METHOD: "DIFFERENT_SIGN_IN_METHOD",
};
